/**
 * workflow.config.js – Project Workflow Configuration
 *
 * Auto-generated by: node workflow/init-project.js
 * Detected tech stack: JavaScript / Node.js
 * Generated at: 2026-03-14T03:20:12.234Z
 *
 * You can customise this file at any time.
 * Re-run: node workflow/init-project.js  to apply changes.
 */

'use strict';

module.exports = {
  // ─── Runtime-Detected (uncomment only to override auto-detection) ─────
  // projectName, techStack, sourceExtensions, and ignoreDirs are auto-detected
  // at runtime by detectTechStack(). No need to configure manually.
  // projectName: 'WorkFlowAgent',
  // techStack: 'JavaScript + Node.js',
  // sourceExtensions: ['.js', '.mjs'],
  // ignoreDirs: ['node_modules', '.git', 'dist', 'build', 'output'],

  // ─── Code Graph ──────────────────────────────────────────────────────────────
  //
  // Controls how CodeGraph builds the symbol index for the project.
  //
  // Three-layer automatic filtering (always active, no config needed):
  //   Layer 1: .gitignore patterns → auto-skips node_modules/, dist/, build/, etc.
  //   Layer 2: Non-code dirs       → auto-skips images/, fonts/, docs/, data/, etc.
  //   Layer 3: Extension check     → only scans files matching sourceExtensions above
  //
  // After these three layers, every collected file is a real code file.
  // No file limit is applied – all code files are indexed for complete coverage.
  //
  // Incremental builds:
  //   CodeGraph caches file mtimes and symbols. On subsequent builds, only files
  //   whose mtime has changed are re-processed. Use /graph build --force for a
  //   full rebuild. The cache is stored at output/.code-graph-cache.json.
  //
  // scopeDirs (optional, for large monorepos only):
  //   Limit scanning to specific sub-directories when you only care about part
  //   of a huge monorepo. Supports exact paths ('src/core') and keyword matching
  //   ('lua' → matches XLua, tolua, lua_modules, etc.). Empty = full scan.
  //
  codeGraph: {
    scopeDirs: [],             // Large monorepo only: ['packages/core', 'lua']. Empty = full scan
  },

  // ─── IDE-First Architecture (ADR-37) ─────────────────────────────────────────
  //
  // Foundational principle: IDE capabilities first, self-built as fallback.
  //
  // When WorkFlowAgent runs inside an IDE (Cursor, VS Code, Claude Code, Windsurf),
  // it auto-detects the IDE environment and:
  //   1. Skips spawning a redundant language server (IDE already has one)
  //   2. Injects "IDE Tool Guidance" into Agent prompts (prefer IDE tools)
  //   3. Retains self-built modules as fallback (CodeGraph, ContextLoader, etc.)
  //
  // Detection is fully automatic via process.env inspection. No config needed.
  // Override only if you need to force standalone mode (e.g., in CI/CD pipelines
  // where VSCODE_PID is inherited but no IDE tools are actually available).
  //
  ide: {
    forceStandalone: false,    // Set to true to disable IDE-first mode entirely
    // forceIDE: 'cursor',     // Force a specific IDE identity (for testing)
  },

  // ─── LLM Tuning ──────────────────────────────────────────────────────────────
  //
  // Fine-tune LLM prompt behaviour for your specific model and context window.
  //
  // hallucinationRiskThreshold (tokens):
  //   When a prompt exceeds this token count, the PromptBuilder enters "degradation
  //   mode" — it progressively drops low-priority context sections (auto-injected
  //   skills, ADR digest) to stay under budget. This prevents sending oversized
  //   prompts that cause hallucination or quality degradation.
  //
  //   Default: 16000 — suitable for 128K-200K context window models.
  //   For smaller models (8K-32K windows), lower this to 6000-10000.
  //   For large-context models (1M+ windows like Gemini), raise to 50000+.
  //
  llm: {
    hallucinationRiskThreshold: 16000,   // Token count that triggers prompt degradation
  },

  // ─── Experience Store ─────────────────────────────────────────────────────────
  //
  // Configures the persistent experience accumulation system.
  //
  // maxCapacity:
  //   Maximum number of experience records to keep. When exceeded on load,
  //   the store evicts the lowest-value entries (sorted by hitCount ascending,
  //   then by createdAt ascending — least-used and oldest first).
  //
  //   Default: 500. Increase for long-running projects with many modules.
  //   Decrease for lightweight projects to save disk and speed up search.
  //
  experienceStore: {
    maxCapacity: 500,                    // Max experience records before eviction
  },

  // ─── Automated Verification Loop ─────────────────────────────────────────────
  //
  // testCommand: Shell command to run the project's real test suite.
  //   Set to null to skip real test execution (AI-only test report).
  //   Examples:
  //     'npm test'           – Node.js / Jest / Mocha
  //     'flutter test'       – Flutter / Dart
  //     'pytest'             – Python
  //     'go test ./...'      – Go
  //     'dotnet test'        – .NET
  //
  testCommand: 'node tests/e2e.test.js',

  // testFramework: Hint for TestCaseExecutor to generate the correct test script format.
  //   'auto'   – auto-detect from package.json / project files (default)
  //   'jest'   – Jest (Node.js)
  //   'mocha'  – Mocha (Node.js)
  //   'vitest' – Vitest (Node.js)
  //   'pytest' – pytest (Python)
  //   'go'     – go test (Go)
  //
  testFramework: 'auto',

  // autoFixLoop: When testCommand is set and tests fail, automatically invoke
  //   DeveloperAgent to fix the failures and re-run tests.
  //   maxFixRounds: maximum fix-and-retest cycles (default: 2)
  //   failOnUnfixed: mark workflow failed when tests still fail after all rounds
  //
  autoFixLoop: {
    enabled: true,
    maxFixRounds: 2,
    failOnUnfixed: false,
  },

  // ─── Three-Layer Skill Loading ─────────────────────────────────────────────
  //
  // Skills are loaded in three priority tiers:
  //   Level 1 – Global:  Always loaded for every task (safety, standards, troubleshooting)
  //   Level 2 – Project: Loaded for all tasks in the current project
  //   Level 3 – Task:    Dynamically matched by keyword from task text
  //
  // Skills in higher tiers have loading priority; lower-tier skills fill remaining
  // token budget. Dependencies declared in skill YAML frontmatter are auto-resolved.

  globalSkills: ['standards', 'troubleshooting', 'bp-coding-best-practices'],

  projectSkills: ['javascript-dev', 'bp-architecture-design'],

  // ─── Built-in Skills ─────────────────────────────────────────────────────────
  builtinSkills: [    {
        name: "workflow-orchestration",
        description: "Multi-agent workflow orchestration SOP",
        domains: [
            "workflow",
            "orchestration"
        ],
        type: "workflow",
        loadLevel: "task"
    },
    {
        name: "code-review",
        description: "Code review checklist and best practices",
        domains: [
            "quality",
            "review"
        ],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "javascript-dev",
        description: "JavaScript development patterns",
        domains: [
            "frontend",
            "backend",
            "javascript"
        ],
        type: "language",
        loadLevel: "project"
    },
    {
        name: "standards",
        description: "Project-wide coding standards, naming conventions, and directory structure rules",
        domains: [
            "general",
            "quality",
            "conventions"
        ],
        type: "standards",
        loadLevel: "global"
    },
    {
        name: "troubleshooting",
        description: "Common errors, root causes, and fix recipes from complaint resolutions",
        domains: [
            "general",
            "debugging",
            "error-handling"
        ],
        type: "troubleshooting",
        loadLevel: "global"
    },
    // ── AEF Best Practice Skills ──────────────────────────────────────────
    {
        name: "bp-coding-best-practices",
        description: "Universal coding best practices: readability, naming, functions, control flow, resource safety",
        domains: ["general", "quality", "coding"],
        type: "best-practice",
        loadLevel: "global"
    },
    {
        name: "bp-architecture-design",
        description: "Architecture design principles: module decomposition, dependency management, data architecture",
        domains: ["architecture", "design"],
        type: "best-practice",
        loadLevel: "project"
    },
    {
        name: "bp-component-design",
        description: "Component-level design: SOLID, interfaces, data models, concurrency, error handling",
        domains: ["design", "component"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "bp-distributed-systems",
        description: "Distributed systems design principles and SDLC checklists",
        domains: ["distributed", "network", "reliability"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "bp-performance-optimization",
        description: "Performance optimization methodology, design principles and concrete rules",
        domains: ["performance", "optimization"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "self-refinement",
        description: "Error-driven feedback loop: distill correction experiences into persistent Rules/Skills",
        domains: ["meta", "feedback", "learning"],
        type: "workflow",
        loadLevel: "task"
    },
    {
        name: "spec-template",
        description: "Structured spec document template (10-chapter format from AEF Spec-First methodology)",
        domains: ["requirements", "specification", "design"],
        type: "workflow",
        loadLevel: "task"
    }
],

  // ─── Default Skills ───────────────────────────────────────────────────────
  defaultSkills: {
    ".js": "javascript-dev"
},

  // ─── Classification Rules ─────────────────────────────────────────────────
  // Auto-detection uses built-in fallback rules for this tech stack.
  // Add custom rules here to override or extend them:
  classificationRules: [],

  // ─── P2-3: Custom Detection Rules ────────────────────────────────────────────
  //
  // Extend the ProjectProfiler's built-in detection rules with your own.
  // User rules are checked BEFORE built-in rules (higher priority).
  //
  // customDetectionRules: {
  //   // Custom framework detection rules
  //   frameworks: [
  //     {
  //       name: 'MyFramework',
  //       category: 'backend',     // 'backend' | 'frontend' | 'fullstack' | 'mobile' | 'game'
  //       lang: 'typescript',
  //       detect: (root, deps) => !!deps['my-framework'],
  //     },
  //   ],
  //   // Custom ORM/data layer detection rules
  //   dataLayer: [
  //     {
  //       name: 'MyORM',
  //       detect: (root, deps) => !!deps['my-orm-package'],
  //     },
  //   ],
  //   // Custom test framework detection rules
  //   testFrameworks: [
  //     {
  //       name: 'MyTestRunner',
  //       detect: (root, deps) => !!deps['my-test-runner'],
  //     },
  //   ],
  // },

  // ─── Git PR Workflow ──────────────────────────────────────────────────────────
  //
  // When enabled, the Orchestrator will automatically:
  //   1. Create a feature branch (feat/<date>-<slug>) before writing code
  //   2. Commit all workflow artifacts at the end of the run
  //   3. Push the branch to remote (if autoPush: true)
  //   4. Create a PR/MR description file (output/pr-description.md)
  //   5. Invoke `gh pr create` (GitHub CLI) or `glab mr create` (GitLab CLI) if available
  //
  // Prerequisites:
  //   - The project must be a git repository (git init)
  //   - For auto PR creation: install GitHub CLI (https://cli.github.com) or GitLab CLI
  //
      git: {
    enabled:    true,
    baseBranch: 'main',
    branchType: 'feat',
    autoPush:   true,
    draft:      true,
    labels:     [],
    reviewers:  [],
  },

  // ─── Dry-Run / Sandbox Mode ───────────────────────────────────────────────────
  //
  // When dryRun: true, ALL file-system writes are intercepted and recorded as
  // pending operations. The real file system is NEVER touched during the run.
  //
  // After the run completes:
  //   - A report is saved to output/dry-run-report.md listing all pending ops
  //   - Call `await orchestrator.sandbox.apply()` to commit the changes
  //   - Call `orchestrator.sandbox.reset()` to discard them
  //
  // Use cases:
  //   - Preview what the workflow would generate before committing
  //   - CI "plan" mode (like Terraform plan)
  //   - Safe exploration of unfamiliar codebases
  //
  sandbox: {
    dryRun: false,            // Set to true to enable dry-run mode
  },

  // ─── MCP (Model Context Protocol) ────────────────────────────────────────────
  //
  // Connect external systems (TAPD, CI/CD, DevTools, Web Search) via MCP adapters.
  // When configured, lifecycle events (WORKFLOW_COMPLETE, WORKFLOW_ERROR) are
  // automatically broadcast to all connected adapters.
  //
  // Supported adapters:
  //   - tapd:            Tencent TAPD project management (stories, bugs, tasks)
  //   - devtools:        CI/CD, code review, PR comments
  //   - webSearch:       Web search and page fetching (tavily / brave / fetch)
  //   - packageRegistry: Query npm/PyPI/crates.io for versions, deprecation, metadata
  //   - securityCVE:     Query OSV.dev for known vulnerabilities (zero API key needed)
  //   - codeQuality:     Real code quality metrics (SonarQube / SonarCloud / local analysis)
  //
  // WebSearch providers:
  //   'tavily' – Best quality, requires API key (https://tavily.com)
  //   'brave'  – Generous free tier, requires API key (https://brave.com/search/api)
  //   'fetch'  – No API key needed, uses DuckDuckGo Lite as fallback
  //
  mcp: {
    // tapd: {
    //   workspaceId: 'your-tapd-workspace-id',
    //   accessToken: 'your-tapd-access-token',
    // },
    // devtools: {
    //   ciApiBase: 'https://ci.example.com',
    //   authToken: 'your-ci-auth-token',
    // },
    webSearch: {
      provider: 'fetch',       // 'tavily' | 'brave' | 'fetch'
      // apiKey: '',            // Required for tavily/brave (or set TAVILY_API_KEY / BRAVE_API_KEY env var)
      maxResults: 5,           // Max search results per query
      timeout: 15000,          // HTTP request timeout in ms
    },
    // PackageRegistry: enabled by default (free, no API key needed)
    // Queries npm/PyPI/crates.io for latest versions, deprecation status, metadata.
    // Set to false to disable: packageRegistry: false
    packageRegistry: {
      defaultRegistry: 'npm',  // 'npm' | 'pypi' | 'crates'
      timeout: 10000,          // HTTP request timeout in ms
    },
    // SecurityCVE: enabled by default (free, no API key needed, powered by OSV.dev)
    // Checks project dependencies against known CVE/vulnerability databases.
    // Set to false to disable: securityCVE: false
    securityCVE: {
      timeout: 15000,          // HTTP request timeout in ms
    },
    // LSP (Language Server Protocol): compiler-accurate code intelligence.
    // Spawns a language server (e.g. typescript-language-server) to provide
    // gotoDefinition, findReferences, getHover, documentSymbols, etc.
    // Requires the language server to be installed globally (see installHint).
    //
    // AUTO-ENABLED by default: if a project file (tsconfig.json, pyproject.toml,
    // go.mod, Cargo.toml) is detected AND the corresponding language server is
    // installed, LSP activates automatically. No config needed.
    // If no server is found, it falls back gracefully to regex-based indexing.
    //
    // Set to false to explicitly disable: lsp: false
    // Supported servers: typescript, pyright, pylsp, gopls, rust-analyzer, omnisharp
    //
    // lsp: {
    //   server: 'typescript',  // Auto-detect if omitted. Force a specific server.
    //   // command: 'custom-lsp-server',  // Override the executable
    //   // args: ['--stdio'],             // Override CLI args
    //   timeout: 30000,        // LSP request timeout in ms
    //   autoDetect: true,      // Auto-detect server from project files
    // },

    // CodeQuality: real code quality metrics for CodeReviewAgent.
    // Enabled by default with 'local' backend (zero config needed).
    // The local backend provides: cyclomatic complexity, code duplication,
    // code smells, deep nesting, and a quality gate – all without external tools.
    //
    // For CI-grade accuracy, configure SonarQube or SonarCloud:
    //   codeQuality: {
    //     backend: 'sonarqube',
    //     baseUrl: 'https://sonar.example.com',
    //     token: 'your-sonar-token',          // or set SONAR_TOKEN env var
    //     projectKey: 'my-project',
    //   }
    //   codeQuality: {
    //     backend: 'sonarcloud',
    //     organization: 'my-org',
    //     token: 'your-sonar-token',
    //     projectKey: 'my-project',
    //   }
    //
    // Set to false to disable: codeQuality: false
    codeQuality: {
      backend: 'local',        // 'local' | 'sonarqube' | 'sonarcloud'
      timeout: 15000,          // HTTP request timeout in ms (SonarQube/SonarCloud only)
    },

    // CIStatus: injects CI/CD pipeline status into DEVELOPER and TESTER stages.
    // Wraps the existing CIIntegration class. Auto-detects GitHub Actions / GitLab CI
    // from git remote URL or environment variables.
    // Enabled by default; disable with ciStatus: false
    //
    // For remote CI polling: set GITHUB_TOKEN or GITLAB_TOKEN environment variable.
    // Without a token, falls back to local CI status (last test results).
    //
    // ciStatus: {
    //   provider: 'auto',     // 'github' | 'gitlab' | 'local' | 'auto'
    //   apiToken: '',         // Or set GITHUB_TOKEN / GITLAB_TOKEN env var
    //   repoSlug: '',         // 'owner/repo' (auto-detected from git remote)
    //   cacheTtlMs: 120000,   // Cache TTL in ms (default: 2min)
    // },

    // LicenseCompliance: checks dependencies for open-source license compatibility.
    // Uses ClearlyDefined API (free, no API key) with local node_modules fallback.
    // Detects risky licenses (GPL, AGPL, SSPL) that may conflict with commercial projects.
    // Enabled by default; disable with licenseCompliance: false
    //
    // licenseCompliance: {
    //   backend: 'clearlydefined',  // 'clearlydefined' | 'local'
    //   maxPackages: 30,            // Max packages to check
    //   timeout: 15000,             // HTTP request timeout in ms
    // },

    // DocGen: API documentation skeleton and CHANGELOG auto-generation.
    // Scans source files for undocumented exports (functions/classes without JSDoc).
    // Generates CHANGELOG.md from git log using conventional commits format.
    // Enabled by default; disable with docGen: false
    //
    // docGen: {
    //   maxFiles: 50,              // Max source files to scan
    //   sourceExts: ['.js', '.ts', '.mjs', '.py'],
    // },

    // LLMCostRouter: cost-aware LLM model routing and budget enforcement.
    // Fetches real-time pricing from OpenRouter API (free, no key needed for pricing).
    // Tracks per-role cost, warns when budget threshold is exceeded.
    // Provides model recommendations optimised for cost/quality/speed.
    // Enabled by default; disable with llmCostRouter: false
    //
    // llmCostRouter: {
    //   budgetUsd: 5.0,           // Per-run budget in USD (default: 5.0)
    //   warnThresholdPct: 80,     // Warn when budget usage exceeds this % (default: 80)
    //   pricingBackend: 'openrouter', // 'openrouter' | 'litellm' | 'fallback'
    //   litellmBaseUrl: 'http://localhost:4000',  // LiteLLM base URL (if using litellm)
    //   cacheTtlMs: 3600000,      // Pricing cache TTL in ms (default: 1h)
    // },

    // ContainerSandbox: Docker/Podman container-based sandboxed execution.
    // Runs tests and code verification in isolated containers with:
    //   - Read-only filesystem mount
    //   - Network isolation (--network=none)
    //   - CPU/memory limits
    //   - Non-root user execution
    // DISABLED by default (requires Docker or Podman installed).
    // Enable with: containerSandbox: true or containerSandbox: {}
    //
    // containerSandbox: {
    //   runtime: 'auto',          // 'docker' | 'podman' | 'auto'
    //   image: null,              // Auto-detected from project files (e.g. node:20-slim)
    //   networkEnabled: false,    // Allow network access in container (default: false)
    //   readonlyMount: true,      // Mount project as read-only (default: true)
    //   defaultTimeoutMs: 120000, // Default execution timeout (default: 2min)
    //   limits: {
    //     cpus: '1.0',            // CPU core limit
    //     memory: '512m',         // Memory limit
    //     pidsLimit: 256,         // Max processes
    //   },
    // },

    // FigmaDesign: extracts UI design tokens and component hierarchy from Figma files.
    // Injects color palette, typography, spacing, shadows, breakpoints, and
    // component tree into ARCHITECT and DEVELOPER stage prompts.
    // Opt-in only (requires Figma Personal Access Token + file key).
    // Enable with: figmaDesign: { accessToken: '...', fileKey: '...' }
    //
    // figmaDesign: {
    //   accessToken: '',         // Or set FIGMA_ACCESS_TOKEN env var
    //   fileKey: '',             // From Figma URL: figma.com/file/<FILE_KEY>/...
    //   nodeId: '',              // Optional: specific page/node ID to extract
    //   timeout: 15000,          // HTTP request timeout in ms
    // },

    // TestInfra: testing infrastructure enhancement.
    // Parses local coverage reports (Istanbul/lcov/Clover) and tracks test history.
    // Detects flaky tests and performance regressions across runs.
    // Optional: integrates with Codecov API for coverage trends.
    // Enabled by default; disable with testInfra: false
    //
    // testInfra: {
    //   thresholds: {
    //     lineCoverage: 80,       // Minimum line coverage %
    //     branchCoverage: 70,     // Minimum branch coverage %
    //     functionCoverage: 80,   // Minimum function coverage %
    //     regressionDelta: -5,    // Alert if coverage drops by more than 5pp
    //   },
    //   flakyThreshold: 2,        // Min fail count to flag as flaky (default: 2)
    //   codecovToken: '',         // Or set CODECOV_TOKEN env var
    //   codecovOwner: '',         // GitHub org/user
    //   codecovRepo: '',          // Repository name
    // },
  },
};
