/**
 * workflow.config.js – Project Workflow Configuration
 *
 * Auto-generated by: node workflow/init-project.js
 * Detected tech stack: JavaScript / Node.js
 * Generated at: 2026-03-14T03:20:12.234Z
 *
 * You can customise this file at any time.
 * Re-run: node workflow/init-project.js  to apply changes.
 */

'use strict';

module.exports = {
  // ─── Project Identity ────────────────────────────────────────────────────
  projectName: 'workflow',
  techStack: 'JavaScript + Node.js',

  // ─── Source Scanning ─────────────────────────────────────────────────────
  sourceExtensions: ['.js', '.mjs'],
  ignoreDirs: ['node_modules', '.git', 'dist', 'build', 'output'],

  // ─── Automated Verification Loop ─────────────────────────────────────────────
  //
  // testCommand: Shell command to run the project's real test suite.
  //   Set to null to skip real test execution (AI-only test report).
  //   Examples:
  //     'npm test'           – Node.js / Jest / Mocha
  //     'flutter test'       – Flutter / Dart
  //     'pytest'             – Python
  //     'go test ./...'      – Go
  //     'dotnet test'        – .NET
  //
  testCommand: 'node tests/e2e.test.js',

  // testFramework: Hint for TestCaseExecutor to generate the correct test script format.
  //   'auto'   – auto-detect from package.json / project files (default)
  //   'jest'   – Jest (Node.js)
  //   'mocha'  – Mocha (Node.js)
  //   'vitest' – Vitest (Node.js)
  //   'pytest' – pytest (Python)
  //   'go'     – go test (Go)
  //
  testFramework: 'auto',

  // autoFixLoop: When testCommand is set and tests fail, automatically invoke
  //   DeveloperAgent to fix the failures and re-run tests.
  //   maxFixRounds: maximum fix-and-retest cycles (default: 2)
  //   failOnUnfixed: mark workflow failed when tests still fail after all rounds
  //
  autoFixLoop: {
    enabled: true,
    maxFixRounds: 2,
    failOnUnfixed: false,
  },

  // ─── Three-Layer Skill Loading ─────────────────────────────────────────────
  //
  // Skills are loaded in three priority tiers:
  //   Level 1 – Global:  Always loaded for every task (safety, standards, troubleshooting)
  //   Level 2 – Project: Loaded for all tasks in the current project
  //   Level 3 – Task:    Dynamically matched by keyword from task text
  //
  // Skills in higher tiers have loading priority; lower-tier skills fill remaining
  // token budget. Dependencies declared in skill YAML frontmatter are auto-resolved.

  globalSkills: ['standards', 'troubleshooting', 'bp-coding-best-practices'],

  projectSkills: ['javascript-dev', 'bp-architecture-design'],

  // ─── Built-in Skills ─────────────────────────────────────────────────────────
  builtinSkills: [    {
        name: "workflow-orchestration",
        description: "Multi-agent workflow orchestration SOP",
        domains: [
            "workflow",
            "orchestration"
        ],
        type: "workflow",
        loadLevel: "task"
    },
    {
        name: "code-review",
        description: "Code review checklist and best practices",
        domains: [
            "quality",
            "review"
        ],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "javascript-dev",
        description: "JavaScript development patterns",
        domains: [
            "frontend",
            "backend",
            "javascript"
        ],
        type: "language",
        loadLevel: "project"
    },
    {
        name: "standards",
        description: "Project-wide coding standards, naming conventions, and directory structure rules",
        domains: [
            "general",
            "quality",
            "conventions"
        ],
        type: "standards",
        loadLevel: "global"
    },
    {
        name: "troubleshooting",
        description: "Common errors, root causes, and fix recipes from complaint resolutions",
        domains: [
            "general",
            "debugging",
            "error-handling"
        ],
        type: "troubleshooting",
        loadLevel: "global"
    },
    // ── AEF Best Practice Skills ──────────────────────────────────────────
    {
        name: "bp-coding-best-practices",
        description: "Universal coding best practices: readability, naming, functions, control flow, resource safety",
        domains: ["general", "quality", "coding"],
        type: "best-practice",
        loadLevel: "global"
    },
    {
        name: "bp-architecture-design",
        description: "Architecture design principles: module decomposition, dependency management, data architecture",
        domains: ["architecture", "design"],
        type: "best-practice",
        loadLevel: "project"
    },
    {
        name: "bp-component-design",
        description: "Component-level design: SOLID, interfaces, data models, concurrency, error handling",
        domains: ["design", "component"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "bp-distributed-systems",
        description: "Distributed systems design principles and SDLC checklists",
        domains: ["distributed", "network", "reliability"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "bp-performance-optimization",
        description: "Performance optimization methodology, design principles and concrete rules",
        domains: ["performance", "optimization"],
        type: "best-practice",
        loadLevel: "task"
    },
    {
        name: "self-refinement",
        description: "Error-driven feedback loop: distill correction experiences into persistent Rules/Skills",
        domains: ["meta", "feedback", "learning"],
        type: "workflow",
        loadLevel: "task"
    },
    {
        name: "spec-template",
        description: "Structured spec document template (10-chapter format from AEF Spec-First methodology)",
        domains: ["requirements", "specification", "design"],
        type: "workflow",
        loadLevel: "task"
    }
],

  // ─── Default Skills ───────────────────────────────────────────────────────
  defaultSkills: {
    ".js": "javascript-dev"
},

  // ─── Classification Rules ─────────────────────────────────────────────────
  // Auto-detection uses built-in fallback rules for this tech stack.
  // Add custom rules here to override or extend them:
  classificationRules: [],

  // ─── Git PR Workflow ──────────────────────────────────────────────────────────
  //
  // When enabled, the Orchestrator will automatically:
  //   1. Create a feature branch (feat/<date>-<slug>) before writing code
  //   2. Commit all workflow artifacts at the end of the run
  //   3. Push the branch to remote (if autoPush: true)
  //   4. Create a PR/MR description file (output/pr-description.md)
  //   5. Invoke `gh pr create` (GitHub CLI) or `glab mr create` (GitLab CLI) if available
  //
  // Prerequisites:
  //   - The project must be a git repository (git init)
  //   - For auto PR creation: install GitHub CLI (https://cli.github.com) or GitLab CLI
  //
      git: {
    enabled:    true,
    baseBranch: 'main',
    branchType: 'feat',
    autoPush:   true,
    draft:      true,
    labels:     [],
    reviewers:  [],
  },

  // ─── Dry-Run / Sandbox Mode ───────────────────────────────────────────────────
  //
  // When dryRun: true, ALL file-system writes are intercepted and recorded as
  // pending operations. The real file system is NEVER touched during the run.
  //
  // After the run completes:
  //   - A report is saved to output/dry-run-report.md listing all pending ops
  //   - Call `await orchestrator.sandbox.apply()` to commit the changes
  //   - Call `orchestrator.sandbox.reset()` to discard them
  //
  // Use cases:
  //   - Preview what the workflow would generate before committing
  //   - CI "plan" mode (like Terraform plan)
  //   - Safe exploration of unfamiliar codebases
  //
  sandbox: {
    dryRun: false,            // Set to true to enable dry-run mode
  },

  // ─── MCP (Model Context Protocol) ────────────────────────────────────────────
  //
  // Connect external systems (TAPD, CI/CD, DevTools) via MCP adapters.
  // When configured, lifecycle events (WORKFLOW_COMPLETE, WORKFLOW_ERROR) are
  // automatically broadcast to all connected adapters.
  //
  // Uncomment and fill in credentials to enable:
  //
  // mcp: {
  //   tapd: {
  //     workspaceId: 'your-tapd-workspace-id',
  //     accessToken: 'your-tapd-access-token',
  //   },
  //   devtools: {
  //     ciApiBase: 'https://ci.example.com',
  //     authToken: 'your-ci-auth-token',
  //   },
  // },
};
