#!/usr/bin/env bash
# init.sh – WorkFlowAgent Development Environment Startup
#
# Generated by: node workflow/init-project.js
# Generated at: 2026-03-20T04:04:50.845Z
# Tech stack:   JS
#
# PURPOSE: This script is run at the START of every Coding Agent session.
#   1. Stops any existing dev server (clean slate)
#   2. Starts the development server
#   3. Runs a basic smoke test to verify the environment is healthy
#
# Usage:
#   bash init.sh          # Start dev server
#   bash init.sh --test   # Start + run smoke test only (no server restart)

set -e

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

echo "=================================================="
echo "  WorkFlowAgent – Init Agent Startup"
echo "  $(date)"
echo "=================================================="

# ── Step 1: Stop existing server ───────────────────────────────────────────
echo ""
echo "[1/3] Stopping existing dev server..."
# TODO: add your dev server stop command here (optional)
echo "      Done"

# ── Step 2: Start dev server ───────────────────────────────────────────────
echo ""
echo "[2/3] Starting dev server..."
# TODO: add your dev server start command here
echo "      Server started (PID: $!)"

# ── Step 3: Smoke test ─────────────────────────────────────────────────────
echo ""
echo "[3/3] Running smoke test..."
# TODO: add a basic smoke test command here
echo "      Smoke test complete"

echo ""
echo "=================================================="
echo "  ✅ Environment ready – proceed with feature work"
echo "=================================================="
