/**
 * workflow.config.js – Project Workflow Configuration
 *
 * Auto-generated by: node workflow/init-project.js
 * Generated at: 2026-03-20T14:56:00.000Z
 *
 * NOTE: projectName, techStack, sourceExtensions, and ignoreDirs are
 * auto-detected at runtime. Uncomment to override if detection is wrong.
 */

'use strict';

module.exports = {
  // ─── Runtime-Detected (uncomment only to override auto-detection) ─────
  // projectName: 'WorkFlowAgent',
  // techStack: 'JavaScript + Node.js',
  // sourceExtensions: ['.js', '.mjs'],
  // ignoreDirs: ['node_modules', '.git', 'dist', 'build', 'output'],

  // ─── Code Graph ──────────────────────────────────────────────────────────
  codeGraph: {
    scopeDirs: [],
  },

  // ─── Automated Verification Loop ─────────────────────────────────────────
  testCommand: null,

  autoFixLoop: {
    enabled: true,
    maxFixRounds: 2,
    failOnUnfixed: false,
  },

  // ─── Built-in Skills ─────────────────────────────────────────────────────
  builtinSkills: [
    {
      name: 'workflow-orchestration',
      description: 'Multi-agent workflow orchestration SOP',
      domains: ['workflow', 'orchestration'],
    },
    {
      name: 'code-review',
      description: 'Code review checklist and best practices',
      domains: ['quality', 'review'],
    },
  ],

  // ─── Default Skills ───────────────────────────────────────────────────────
  defaultSkills: {},

  // ─── Classification Rules ─────────────────────────────────────────────────
  classificationRules: [],
};
